services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - spring-microservice

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - spring-microservice

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      - spring-microservice

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
        - spring-microservice

  config-service:
    container_name: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8763:8763"
    depends_on:
      - eureka-server
    networks:
      - spring-microservice
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8762:8762"
    depends_on:
      - eureka-server
    networks:
      - spring-microservice
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hungnd
      SPRING_DATASOURCE_PASSWORD: 123abc
      SPRING_APPLICATION_NAME: auth-service

  department-service-1:
    container_name: department-service-1
    build:
      context: ./department-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hungnd
      SPRING_DATASOURCE_PASSWORD: 123abc
      SPRING_APPLICATION_NAME: department-service

  department-service-2:
    container_name: department-service-2
    build:
      context: ./department-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hungnd
      SPRING_DATASOURCE_PASSWORD: 123abc
      SPRING_APPLICATION_NAME: department-service

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hungnd
      SPRING_DATASOURCE_PASSWORD: 123abc
      SPRING_APPLICATION_NAME: account-service

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - account-service
      - department-service-1
      - department-service-2
    networks:
      - spring-microservice

networks:
  spring-microservice:
    driver: bridge